@startuml

scale 0.3

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

/'
  Definition of microgrid part
'/

class Microgrid <<ontomg>>
class  Branch <<ontomg>>
class ESBranch <<ontomg>>
class DERBranch <<ontomg>>
class ELBranch <<ontomg>>
class InfraBranch <<ontomg>>

class EnergyStorage <<ontomg>>
class BranchController <<ontomg>>

class BranchSwitch <<ontomg>>
class NonRenewableDERBranch <<ontomg>>
class RenewableDERBranch <<ontomg>>
class SolarPowerBranch <<ontomg>>
class SmallWindPowerBranch <<ontomg>>
class MicroturbinesBranch <<bem>>
class SolarHybridBranch <<bem>>
class WindHybridBranch <<bem>>
class PhotovoltaicBranch <<bem>>


class Converter <<ontomg>>
class Inverter <<ontomg>>
class AcDcConverter <<ontomg>>
class WindTurbine <<ontomg>>
class SolarCell <<ontomg>>
class FuelCellBranch <<ontomg>>
class CHPPPowerBranch <<ontomg>>
class DieselGenerator <<ontomg>>
class MonophasicInverter <<ontomg>>
class TriphasicInverter <<ontomg>>

class ConductingEquipement <<cim>>
class RectifierInverter <<cim>>

class HydroPowerBranch <<bem>>
class GeoThermalBranch <<bem>>
class BiomassBranch <<bem>>
class OilBranch <<bem>>
class GasBranch <<bem>>
class CoalBranch <<bem>>
class NuclearBranch <<bem>>
class MicroCHPPPowerBranch <<bem>>
class ReciprocatingBranch <<bem>>
class StirlingBranch <<bem>>

class IfcDistributionCircuit <<ifc4>>

class IfcDistributionSystem <<ifc4>>
class IfcSystem <<ifc>>
class IfcDistributionElement <<ifc>>
class IfcFlowController <<ifc>>
class IfcElectricalFlowStorageDevice <<ifc4>>
class IfcElectricalFlowStorageDeviceType <<ifc>>

class IfcFlowMovingDevice <<ifc>>
class IfcEnergyConversionDevice <<ifc>>

class Property <<ssn>>
class FeatureOfInterest <<ssn>>

EconomicProperties <<bem>>
PhysicsProperties <<bem>>
class OccupantStateProperties <<bem>>

/'
    Incorporation of micro-grid description to the building
'/


Property <|-- EconomicProperties
Property <|-- PhysicsProperties
Property <|-- OccupantStateProperties

Microgrid --> Property: hit2gap:hasProperty
FeatureOfInterest <|-- Microgrid

Microgrid --> Branch: ontomg:hasBranch
Branch --> Branch: ontomg:isComposedOf
Branch <|-- ESBranch
Branch <|-- DERBranch
Branch <|-- ELBranch
Branch <|-- InfraBranch

Branch --> BranchController: hit2gap:hasA


IfcDistributionSystem <|-- IfcDistributionCircuit
BranchController <|-- IfcFlowController
ConductingEquipement <|-- BranchController
InfraBranch <|-- IfcDistributionCircuit
ESBranch <|-- IfcDistributionElement
ELBranch <|-- IfcDistributionElement
EnergyStorage <|-- IfcElectricalFlowStorageDevice
ELBranch <|-- IfcFlowMovingDevice
ELBranch <|-- IfcEnergyConversionDevice

IfcSystem <|-- IfcDistributionElement

DERBranch --> BranchSwitch: ontomg:hasA
DERBranch<|-- RenewableDERBranch
DERBranch<|-- NonRenewableDERBranch

RenewableDERBranch <|-- SolarPowerBranch
RenewableDERBranch <|-- SmallWindPowerBranch
RenewableDERBranch <|-- HydroPowerBranch
RenewableDERBranch <|-- GeoThermalBranch
RenewableDERBranch <|-- BiomassBranch
RenewableDERBranch <|-- MicroturbinesBranch
RenewableDERBranch <|-- SolarHybridBranch
RenewableDERBranch <|-- WindHybridBranch
RenewableDERBranch <|-- PhotovoltaicBranch

SolarPowerBranch--> SolarCell: ontomg:hasA
SmallWindPowerBranch --> WindTurbine: ontomg:hasA

RegulatingCongEq <|-- WindTurbine
RegulatingCongEq <|-- SolarCell

SolarPowerBranch --> Converter: ontomg:hasA
SmallWindPowerBranch --> Converter: ontomg:hasA

RectifierInverter <|-- Converter
Converter <|-- Inverter
Converter <|-- AcDcConverter

Inverter <|-- MonophasicInverter
Inverter <|-- TriphasicInverter


NonRenewableDERBranch <|-- OilBranch
NonRenewableDERBranch <|-- GasBranch
NonRenewableDERBranch <|-- CoalBranch
NonRenewableDERBranch <|-- NuclearBranch
OilBranch <|-- FuelCellBranch
NonRenewableDERBranch <|-- CHPPPowerBranch
NonRenewableDERBranch <|-- MicroCHPPPowerBranch
NonRenewableDERBranch <|-- ReciprocatingBranch
NonRenewableDERBranch <|-- StirlingBranch


FuelCellBranch --> Converter: ontomg:hasA
FuelCellBranch --> DieselGenerator: ontomg:hasA

IfcElectricalFlowStorageDevice --> IfcElectricalFlowStorageDeviceType: owl:equivalentClass


@enduml
