@startuml

scale 0.5

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

class BuildingAppliance <<hit2gap>>
class IfcFlowTerminal <<ifc>>
class Monitoring <<hit2gap>>
class Wereable <<hit2gap>>
class Smartwatch <<hit2gap>>
class Smartphone <<hit2gap>>

class IfcActuator <<ifc>>
class IfcAlarm <<ifc>>
class IfcController <<ifc>>
class IfcSensor <<ifc>>
class Meter <<hit2gap>>

class IfcFlowStorageDevice <<ifc>>
class IfcFlowMovingDevice <<ifc>>
class IfcFlowController <<ifc>>
class IfcFlowTreatmentDevice <<ifc>>
class IfcEnergyConversionDevice <<ifc>>


BuildingAppliance <|-- IfcFlowTerminal
BuildingAppliance <|-- Monitoring
BuildingAppliance <|-- Wereable
BuildingAppliance --> IfcDistributionElement: hit2gap:locatedIn
BuildingAppliance <|-- IfcFlowStorageDevice
BuildingAppliance <|-- IfcFlowMovingDevice
BuildingAppliance <|-- IfcFlowController
BuildingAppliance <|-- IfcFlowTreatmentDevice
BuildingAppliance <|-- IfcEnergyConversionDevice

Wereable <|-- Smartwatch
Wereable <|-- Smartphone

Monitoring <|-- IfcSensor
Monitoring <|-- IfcActuator
Monitoring <|-- IfcAlarm
Monitoring <|-- IfcController
Monitoring <|-- Meter



@enduml
