@startuml

scale 0.6

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

class Actions <<HIT2GAP>>{

}

class SystemActions<<HIT2GAP>>{

}

class Device <<SSN>>{

}

class Alert <<HIT2GAP>>{

}

class Inaction <<HIT2GAP>>{

}

class Feedback <<HIT2GAP>>{

}


class OccupantDiscomfort <<HIT2GAP>>{

}

class WindowCoverings <<bem>> 


class IfcActuator <<ifc4>>
class IfcActuatorType <<ifc>>

class IfcWindow <<ifc>>
class IfcZone <<ifc>>

class IfcDistributionControlElement <<ifc>>

class IfcEnergyConversionDevice <<ifc>> {
  hasSetPoint xsd:boolean
}

class IfcOccupant <<IFC>>{
  age xsd:double
  gender xsd:string
  lifestyle xsd:string
  jobType xsd:string
}

Actions <|-- SystemActions
Actions <|-- Inaction

Actions <|-- Feedback
Actions <|-- OccupantEvent

Actions --> OccupantDiscomfort: hit2gap:provoke
SystemActions --> IfcDistributionControlElement:hit2gap_changes
IfcDistributionControlElement --> Alert: hit2gap:receivesAlert
SystemActions --> Device: hit2gap:actuateOver
SystemActions --> IfcActuator: hit2gap:actuateOver
IfcOccupant --> Actions: hit2gap:performsAction
IfcWindow --> WindowCoverings: hit2gap:hasCoverings
IfcActuator --> IfcWindow: hit2gap:OpenClose
IfcActuator --> WindowCoverings: hit2gap:OpenClose
IfcEnergyConversionDevice --> IfcZone: hit2gap:InputOutput

IfcActuator --> IfcActuatorType: owl:equivalentClass


@enduml
