@startuml

scale 0.3

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

class BuildingAppliance <<bem>>

class StaticBuildingAppliance <<bem>>
class MobileBuildingAppliance <<bem>>

class Observation <<ssn>>  {
  externalStorageID xsd:string
}

class MobileBuildingApplianceLocationObservation <<bem>>

class IfcFlowTerminal <<ifc>>
class Monitoring <<bem>>
class Wereable <<bem>>
class Smartwatch <<bem>>
class Smartphone <<bem>>

class IfcZone <<ifc>>
class IfcActuator <<ifc4>>
class IfcActuatorType <<ifc>>

class IfcAlarm <<ifc4>>
class IfcAlarmType <<ifc>>


class IfcSensor <<ifc4>>
class IfcSensorType <<ifc>>

class Meter <<bem>>

class IfcFlowStorageDevice <<ifc>>
class IfcFlowMovingDevice <<ifc>>
class IfcFlowController <<ifc>>
class IfcFlowTreatmentDevice <<ifc>>
class IfcEnergyConversionDevice <<ifc>> {
  hasSetPoint xsd:boolean
}

class IfcElectricalFlowStorageDevice <<ifc4>>
class IfcElectricalFlowStorageDeviceType <<ifc>>
class IfcTank <<ifc4>>
class IfcTankType <<ifc>>


class ELBranch <<ontomg>>
class ESBranch <<ontomg>>
class BranchController <<ontomg>>


class PhysicalMedium <<bem>>
class Oil <<bem>>
class Gas <<bem>>
class Water <<bem>>
class Air <<bem>>
class Steam <<bem>>
class Radiation <<bem>>

BuildingAppliance <|-- StaticBuildingAppliance 
BuildingAppliance <|-- MobileBuildingAppliance 

StaticBuildingAppliance <|-- IfcFlowTerminal
StaticBuildingAppliance <|-- Monitoring
MobileBuildingAppliance <|-- Wereable
StaticBuildingAppliance --> IfcZone: hit2gap:isLocatedIn
BuildingAppliance --> BuildingAppliance: hit2gap:contains
Monitoring --> BuildingAppliance: hit2gap:MeasureInputOutput
IfcEnergyConversionDevice --> IfcZone: hit2gap:InputOutput
StaticBuildingAppliance <|-- IfcFlowStorageDevice
IfcFlowStorageDevice <|-- IfcElectricalFlowStorageDevice
IfcFlowStorageDevice <|-- IfcTank
StaticBuildingAppliance <|-- IfcFlowMovingDevice
StaticBuildingAppliance <|-- IfcFlowController
StaticBuildingAppliance <|-- IfcFlowTreatmentDevice
StaticBuildingAppliance <|-- IfcEnergyConversionDevice
Observation <|-- MobileBuildingApplianceLocationObservation
MobileBuildingAppliance --> MobileBuildingApplianceLocationObservation: hit2gap:wasLocated
BranchController <|-- IfcFlowController
ESBranch <|-- IfcElectricalFlowStorageDevice
ELBranch <|-- IfcFlowMovingDevice
ELBranch <|-- IfcEnergyConversionDevice

Wereable <|-- Smartwatch
Wereable <|-- Smartphone

Monitoring <|-- IfcSensor
Monitoring <|-- IfcActuator
Monitoring <|-- IfcAlarm
Monitoring <|-- Meter

PhysicalMedium <|-- Oil
PhysicalMedium <|-- Gas
PhysicalMedium <|-- Water
PhysicalMedium <|-- Air
PhysicalMedium <|-- Steam
PhysicalMedium <|-- Radiation

IfcFlowMovingDevice --> PhysicalMedium: hit2gap:transports
IfcEnergyConversionDevice --> PhysicalMedium: hit2gap:consumes
IfcEnergyConversionDevice --> PhysicalMedium: hit2gap:produces
IfcFlowStorageDevice --> PhysicalMedium: hit2gap:stores
IfcFlowController --> PhysicalMedium: hit2gap:controls
IfcFlowTerminal --> PhysicalMedium: hit2gap:consumes

IfcActuator --> IfcActuatorType: owl:equivalentClass
IfcAlarm --> IfcAlarmType: owl:equivalentClass
IfcSensor --> IfcSensorType: owl:equivalentClass
IfcElectricalFlowStorageDevice --> IfcElectricalFlowStorageDeviceType: owl:equivalentClass
IfcTank --> IfcTankType: owl:equivalentClass


@enduml
