@startuml

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

/'
 Definition of the classes referring the SSN-core part
'/
class System <<ssn>>
class Device <<ssn>>
class Sensor <<ssn>>
class Observation <<ssn>>
class FeatureOfInterest <<ssn>>
class Property <<ssn>>
class SensorOutput <<ssn>>
class ObservationValue <<ssn>>
class Instant <<time>>{
    time:inXSDDateTime [xsd:DateTime]
}
class DateTimeInterval <<time>>{
    time:inXSDDateTime [xsd:DateTime]
}
class Unit <<QUDT>>

/'
  Definition of the Geo-core part
'/
class _Feature <<geo>>
class _Geometry <<geo>>
class Point <<geo>>
class Polygon <<geo>>
class Hemisphere <<hit2gap>>
class Climate <<hit2gap>>
class Northerm <<(I,orchid),hit2gap>>
class Southern <<(I,orchid),hit2gap>>
class Tropical <<hit2gap>>
class Arid <<hit2gap>>
class Temperate <<hit2gap>>
class Cold <<hit2gap>>
class Polar <<hit2gap>>


/'
  Definition of the Feature of interest classes
'/
class Building <<hit2gap>>
class IfcElement <<ifc>>
class IfcBuildingElement <<ifc>>
class IfcDistirbutionElement <<ifc>>
class IfcZones <<ifc>>
class Orientation <<hit2gap>>

class North <<(I,orchid),hit2gap>>
class South <<(I,orchid),hit2gap>>
class West <<(I,orchid),hit2gap>>
class East <<(I,orchid),hit2gap>>
class North_East <<(I,orchid),hit2gap>>
class North_West <<(I,orchid),hit2gap>>
class South_East <<(I,orchid),hit2gap>>
class South_West <<(I,orchid),hit2gap>>

/'
  Building types class definition
'/
class Agricultural <<hit2gap>>
class Commercial <<hit2gap>>
class Residential  <<hit2gap>>
class Educational <<hit2gap>>
class Industrial <<hit2gap>>
class Religious <<hit2gap>>
class Public <<hit2gap>>
class Transports <<hit2gap>>

/'
  Building Zones types definition
'/

class Room <<hit2gap>>
class Floor <<hit2gap>>
class Desk <<hit2gap>>
class Subterranean <<hit2gap>>
class Ground <<hit2gap>>


/'
 Definition of Building Elements subclasses
'/

class IfcBeam <<ifc>>
class IfcChimmey <<ifc>>
class IfcColumn <<ifc>>
class IfcCovering <<ifc>>
class IfcCurtainWall <<ifc>>
class IfcDoor <<ifc>>
class IfcFooting <<ifc>>
class IfcMember <<ifc>>
class IfcPile <<ifc>>
class IfcPlate <<ifc>>
class IfcRailing <<ifc>>
class IfcRamp <<ifc>>
class IfcRampFlight <<ifc>>
class IfcRoof <<ifc>>
class IfcShadingDevice <<ifc>>
class IfcSlab <<ifc>>
class IfcStair <<ifc>>
class IfcStairFlight <<ifc>>
class IfcWall <<ifc>>
class IfcWindow <<ifc>>
class IfcSpace <<ifc>>


/'
 Definition of Spaces  Types
'/

class Office <<hit2gap>>
class CirculationArea <<hit2gap>>
class WetArea <<hit2gap>>
class ConferenceRoom <<hit2gap>>
class Balcony <<hit2gap>>
class Kitchen <<hit2gap>>
class Toilets <<hit2gap>>
class Bathroom <<hit2gap>>
class RestRoom <<hit2gap>>
class Canteen <<hit2gap>>
class Cafeteria <<hit2gap>>

/'
 Definition of IfcWindows
'/

class Curtains <<hit2gap>>
class Blinds <<hit2gap>>
class Shutters <<hit2gap>>
class Shades <<hit2gap>>



/'
 Definition of the SSN model to model the sensor observation of the building
 facilities
'/

System --> System: ssn:hasSubSystem
System <|-- Device
Device <|-- Sensor
Sensor --> Observation: ssn:observedBy
Sensor --> Property: ssn:observes
Observation --> FeatureOfInterest: ssn:featureOfInterest
FeatureOfInterest --> Property: ssn:Property
Observation --> SensorOutput: ssn:ObservationResult
SensorOutput --> ObservationValue: ssn:hasValue
ObservationValue --> Unit: qudt:unit
Observation --> Instant: ssn:observationResultTime
Observation --> DateTimeInterval: ssn:observationResultTime

/'
  Definition of the geospatial part using GeoOWL ontology
'/

_Feature --> _Geometry: geo:where
_Geometry <|-- Point
_Geometry <|-- Polygon

_Feature <|-- FeatureOfInterest
_Feature <|-- System

_Feature --> Hemisphere: hit2gap:locatedInHemisphere
_Feature --> Climate: hit2gap:locatedInClimate

Hemisphere ..[#orchid] Northerm
Hemisphere ..[#orchid] Southern

Climate <|-- Tropical
Climate <|-- Arid
Climate <|-- Temperate
Climate <|-- Cold
Climate <|-- Polar

/'
  Definition of the types of FoIs
'/

FeatureOfInterest <|-- Building
FeatureOfInterest <|-- BuildingInfrastructure
FeatureOfInterest <|-- BuildingElements

Building -->IfcZones: hit2gap:contains
IfcZones --> IfcElement: hit2gap:contains
IfcElement <|-- IfcDistributionElement
IfcElement <|-- IfcBuildingElement

IfcDistributionElement --> IfcBuildingElement: hit2gap:contains

Building <|-- Agricultural
Building <|-- Commercial
Building <|-- Residential
Building <|-- Educational
Building <|-- Industrial
Building <|-- Religious
Building <|-- Public
Building <|-- Transports

IfcZones <|-- Room
IfcZones <|-- Floor
IfcZones <|-- Desk

Floor <|-- Subterranean
Floor <|-- Ground

IfcBuildingElement <|-- IfcBeam
IfcBuildingElement <|-- IfcChimmey
IfcBuildingElement <|-- IfcColumn
IfcBuildingElement <|-- IfcCovering
IfcBuildingElement <|-- IfcCurtainWall
IfcBuildingElement <|-- IfcDoor
IfcBuildingElement <|-- IfcFooting
IfcBuildingElement <|-- IfcMember
IfcBuildingElement <|-- IfcPile
IfcBuildingElement <|-- IfcPlate
IfcBuildingElement <|-- IfcRailing
IfcBuildingElement <|-- IfcRamp
IfcBuildingElement <|-- IfcRampFlight
IfcBuildingElement <|-- IfcRoof
IfcBuildingElement <|-- IfcShadingDevice
IfcBuildingElement <|-- IfcSlab
IfcBuildingElement <|-- IfcStair
IfcBuildingElement <|-- IfcStairFlight
IfcBuildingElement <|-- IfcWall
IfcBuildingElement <|-- IfcWindow
IfcBuildingElement <|-- IfcSpace


IfcSpace <|-- Office
IfcSpace <|-- CirculationArea
IfcSpace <|-- WetArea
IfcSpace <|-- ConferenceRoom
IfcSpace <|-- Balcony
IfcSpace <|-- Kitchen
IfcSpace <|-- Toilets
IfcSpace <|-- Bathroom
IfcSpace <|-- RestRoom
IfcSpace <|-- Canteen
IfcSpace <|-- Cafeteria

IfcWindow <|-- Curtains
IfcWindow <|-- Blinds
IfcWindow <|-- Shutters
IfcWindow <|-- Shades


IfcDistributionElement <|-- IfcDistributionControlElement

Building --> Orientation: hit2gap:hasOrientation

Orientation..[#orchid] North
Orientation..[#orchid] South
Orientation..[#orchid] West
Orientation..[#orchid] East
Orientation..[#orchid] North_East
Orientation..[#orchid] North_West
Orientation..[#orchid] South_East
Orientation..[#orchid] South_West



@enduml