@startuml

scale 0.5

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green


/'
  Definition of the Feature of interest classes
'/
class IfcBuilding <<ifc>>
class IfcElement <<ifc>>
class IfcBuildingElement <<ifc>>
class IfcDistirbutionElement <<ifc>>
class IfcElementComponent <<ifc>>
class IfcDistributionControlElement <<ifc>>
class IfcDistributionFlowElement <<ifc>>
class IfcZone <<ifc>>
class IfcSpatialZone <<ifc>>

class Sensor <<ogc>>
class IfcFlowInstrument <<ifc>>
class IfcProtectiveDeviceTrippingUnit <<ifc>>
class IfcSensor <<ifc>>
class IfcUnitaryControlElement <<ifc>>
class IfcFlowTerminal <<ifc>>

class BuildingAppliance <<hit2gap>>

class Monitoring <<hit2gap>>
class Wereable <<hit2gap>>

class Smartwatch <<hit2gap>>
class Smartphone <<hit2gap>>

class Meter <<hit2gap>>

class IfcActuator <<ifc>>
class IfcAlarm <<ifc>>
class IfcController <<ifc>>

/'
  Building types class definition
'/
class Agricultural <<hit2gap>>
class Commercial <<hit2gap>>
class Residential  <<hit2gap>>
class Educational <<hit2gap>>
class Industrial <<hit2gap>>
class Religious <<hit2gap>>
class Public <<hit2gap>>
class Transports <<hit2gap>>

/'
  Building Zones types definition
'/

class Room <<hit2gap>>
class Floor <<hit2gap>>
class Desk <<hit2gap>>
class Subterranean <<hit2gap>>
class Ground <<hit2gap>>



/'
  Definition of the types of FoIs
'/

FeatureOfInterest <|-- IfcBuilding
FeatureOfInterest <|-- BuildingAppliance
FeatureOfInterest <|-- IfcBuildingElement

Sensor<|-- BuildingAppliance

IfcBuilding <|-- IfcSpatialElement
IfcSpatialElement <|-- IfcSpatialZone

BuildingAppliance --> IfcDistirbutionElement: hit2gap:containsElement

IfcBuilding -->IfcSpatialZone: hit2gap:contains
IfcBuilding -->IfcZone: hit2gap:contains
IfcSpatialZone --> IfcElement: hit2gap:contains

IfcElement <|-- IfcDistributionElement
IfcElement <|-- IfcBuildingElement
IfcElement <|-- IfcElementComponent

IfcDistirbutionElement <|-- IfcDistributionControlElement
IfcDistirbutionElement <|-- IfcDistributionFlowElement

IfcDistributionElement --> IfcBuildingElement: hit2gap:contains

BuildingType <|-- Agricultural
BuildingType <|-- Commercial
BuildingType <|-- Residential
BuildingType <|-- Educational
BuildingType <|-- Industrial
BuildingType <|-- Religious
BuildingType <|-- Public
BuildingType <|-- Transports

IfcBuilding --> BuildingType: hit2gap:hasType

BuildingAppliance <|-- IfcFlowTerminal
BuildingAppliance <|-- Monitoring
BuildingAppliance <|-- Wereable

Wereable <|-- Smartwatch
Wereable <|-- Smartphone

Monitoring <|-- IfcSensor
Monitoring <|-- IfcActuator
Monitoring <|-- IfcAlarm
Monitoring <|-- IfcController
Monitoring <|-- Meter

IfcZone <|-- Room
IfcZone <|-- Floor
IfcZone <|-- Desk

Floor <|-- Subterranean
Floor <|-- Ground

IfcDistributionElement <|-- IfcDistributionControlElement
IfcDistributionControlElement <|-- IfcActuator
IfcDistributionControlElement <|-- IfcAlarm
IfcDistributionControlElement <|-- IfcController
IfcDistributionControlElement <|-- IfcFlowInstrument
IfcDistributionControlElement <|-- IfcProtectiveDeviceTrippingUnit
IfcDistributionControlElement <|-- IfcSensor
IfcDistributionControlElement <|-- IfcUnitaryControlElement

IfcDistributionControlElement <--> Sensor: owl:equivalenClass

@enduml