@startuml

scale 0.5

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green


/'
  Definition of the Feature of interest classes
'/
class FeatureOfInterest <<ssn>>

class Observation <<ssn>>  {
  externalStorageID xsd:string
}

class MobileBuildingApplianceLocationObservation <<hit2gap>>

class IfcBuilding <<ifc>>
class IfcElement <<ifc>>
class IfcSpatialElement <<h2gifc4>>
class Microgrid <<ontomg>>
class IfcSpatialStructureElement <<ifc>>{
  hasSpatialStructureCapacity: xsd:double;
}
class IfcBuildingElement <<ifc>>
class IfcElementComponent <<ifc>>
class IfcDistributionControlElement <<ifc>>
class IfcDistributionFlowElement <<ifc>>
class IfcZone <<ifc>>
class IfcSpatialZone <<h2gifc4>>

class IfcFlowInstrument <<ifc4>>
class IfcFlowInstrumentType <<ifc>>

class IfcSensor <<ifc4>>
class IfcSensorType <<ifc>>

class IfcProtectiveDeviceTrippingUnit <<h2gifc4>>

class IfcUnitaryControlElement <<h2gifc4>>
class IfcFlowTerminal <<ifc>>

class IfcFlowStorageDevice <<ifc4>>
class IfcFlowStorageDeviceType <<ifc>>

class IfcFlowTreatmentDevice <<ifc>>

class IfcEnergyConversionDevice <<ifc>> {
  hasSetPoint xsd:boolean
}

class IfcFlowController <<ifc>>

class IfcFlowMovingDevice <<ifc>>

class BuildingAppliance <<hit2gap>>
class BuildingType <<hit2gap>>
class StaticBuildingAppliance <<hit2gap>>
class MobileBuildingAppliance <<hit2gap>>

class Monitoring <<hit2gap>>
class Wereable <<hit2gap>>

class Smartwatch <<hit2gap>>
class Smartphone <<hit2gap>>

class Meter <<hit2gap>>

class IfcActuator <<ifc4>>
class IfcActuatorType <<ifc>>

class IfcAlarm <<ifc4>>
class IfcAlarmType <<ifc>>

class IfcController <<ifc4>>
class IfcControllerType <<ifc>>

class ELBranch <<ontomg>>
class EnergyStorage <<ontomg>>
class BranchController <<ontomg>>

/'
  Building types class definition
'/
class Agricultural <<hit2gap>>
class Commercial <<hit2gap>>
class Residential  <<hit2gap>>
class Educational <<hit2gap>>
class Industrial <<hit2gap>>
class Religious <<hit2gap>>
class Public <<hit2gap>>
class Transports <<hit2gap>>

/'
  Building Zones types definition
'/

class Room <<hit2gap>>
class Floor <<hit2gap>>
class OpenSpace <<hit2gap>>
class Desk <<hit2gap>>
class Subterranean <<hit2gap>>
class Ground <<hit2gap>>

class IfcDistributionElement <<ifc>>
class DistributionElementState <<hit2gap>>
class DiscreteState <<hit2gap>>
class ContinousState <<hit2gap>>

class IfcBuildingStorey <<ifc>>
class IfcSite <<ifc>>
class IfcSpace <<ifc>>
class SpaceCapacity <<hit2gap>>

class Orientation <<hit2gap>>

class North <<(I,orchid),hit2gap>>
class South <<(I,orchid),hit2gap>>
class West <<(I,orchid),hit2gap>>
class East <<(I,orchid),hit2gap>>
class North_East <<(I,orchid),hit2gap>>
class North_West <<(I,orchid),hit2gap>>
class South_East <<(I,orchid),hit2gap>>
class South_West <<(I,orchid),hit2gap>>


/'
  Definition of the types of Physical Medium
'/

class PhysicalMedium <<hit2gap>>
class Oil <<hit2gap>>
class Gas <<hit2gap>>
class Water <<hit2gap>>
class Air <<hit2gap>>
class Steam <<hit2gap>>
class Radiation <<hit2gap>>

/'
  Definition of the types of FoIs
'/

FeatureOfInterest <|-- IfcBuilding
FeatureOfInterest <|-- BuildingAppliance
FeatureOfInterest <|-- IfcElement
FeatureOfInterest <|-- Microgrid
FeatureOfInterest <|-- IfcSpatialElement


IfcSpatialStructureElement <|-- IfcBuilding
IfcSpatialElement <|-- IfcSpatialStructureElement
IfcSpatialElement <|-- IfcSpatialZone

IfcSpatialStructureElement --> SpaceCapacity: hit2gap:hasCapacity


IfcSpatialStructureElement <|-- IfcBuildingStorey
IfcSpatialStructureElement <|-- IfcSite
IfcSpatialStructureElement <|-- IfcSpace



IfcBuilding -->IfcSpatialZone: hit2gap:contains
IfcSpatialZone --> IfcElement: hit2gap:contains


IfcSite --> IfcSite: hit2gap:contains
IfcSite --> IfcBuilding: hit2gap:contains
IfcBuilding --> IfcBuilding: hit2gap:contains
IfcBuildingStorey -->IfcSpace: hit2gap:contains
IfcZone -->IfcZone: hit2gap:contains
IfcZone -->IfcSpace: hit2gap:contains

IfcBuilding -->IfcSpace: hit2gap:contains
IfcBuilding --> IfcBuildingStorey: hit2gap:contains

IfcSite --> Orientation: hit2gap:hasOrientation
IfcBuilding --> Orientation: hit2gap:hasOrientation

Orientation..[#orchid] North
Orientation..[#orchid] South
Orientation..[#orchid] West
Orientation..[#orchid] East
Orientation..[#orchid] North_East
Orientation..[#orchid] North_West
Orientation..[#orchid] South_East
Orientation..[#orchid] South_West


IfcElement <|-- IfcDistributionElement
IfcElement <|-- IfcBuildingElement
IfcElement <|-- IfcElementComponent

IfcDistributionElement <|-- IfcDistributionControlElement
IfcDistributionElement <|-- IfcDistributionFlowElement

IfcDistributionFlowElement <|-- IfcFlowStorageDevice
IfcDistributionFlowElement <|-- IfcFlowMovingDevice
IfcDistributionFlowElement <|-- IfcFlowController
IfcDistributionFlowElement <|-- IfcFlowTerminal
IfcDistributionFlowElement <|-- IfcFlowTreatmentDevice
IfcDistributionFlowElement <|-- IfcEnergyConversionDevice

IfcDistributionElement --> DistributionElementState: hit2gap:hasState
DistributionElementState <|-- ContinousState
DistributionElementState <|-- DiscreteState

IfcDistributionElement --> IfcBuildingElement: hit2gap:contains

BuildingType <|-- Agricultural
BuildingType <|-- Commercial
BuildingType <|-- Residential
BuildingType <|-- Educational
BuildingType <|-- Industrial
BuildingType <|-- Religious
BuildingType <|-- Public
BuildingType <|-- Transports

IfcBuilding --> BuildingType: hit2gap:hasType

BuildingAppliance <|-- StaticBuildingAppliance 
BuildingAppliance <|-- MobileBuildingAppliance

StaticBuildingAppliance <|-- IfcFlowTerminal
StaticBuildingAppliance <|-- Monitoring
MobileBuildingAppliance <|-- Wereable

BuildingAppliance --> BuildingAppliance: hit2gap:contains
StaticBuildingAppliance --> IfcZone: hit2gap:isLocatedIn
Monitoring --> BuildingAppliance: hit2gap:MeasureInputOutput
IfcEnergyConversionDevice --> IfcZone: hit2gap:InputOutput
StaticBuildingAppliance <|-- IfcFlowStorageDevice
StaticBuildingAppliance <|-- IfcFlowMovingDevice
StaticBuildingAppliance <|-- IfcFlowController
StaticBuildingAppliance <|-- IfcFlowTreatmentDevice
StaticBuildingAppliance <|-- IfcEnergyConversionDevice
Observation <|-- MobileBuildingApplianceLocationObservation
MobileBuildingAppliance --> MobileBuildingApplianceLocationObservation: hit2gap:wasLocated

BranchController <|-- IfcFlowController
EnergyStorage <|-- IfcElectricalFlowStorageDevice
ELBranch <|-- IfcFlowMovingDevice
ELBranch <|-- IfcEnergyConversionDevice


Wereable <|-- Smartwatch
Wereable <|-- Smartphone

Monitoring <|-- IfcSensor
Monitoring <|-- IfcActuator
Monitoring <|-- IfcAlarm
Monitoring <|-- Meter

IfcSpace <|-- Office
IfcSpace <|-- CirculationArea
IfcSpace <|-- WetArea
IfcSpace <|-- ConferenceRoom
IfcSpace <|-- Balcony
IfcSpace <|-- Kitchen
IfcSpace <|-- Toilets
IfcSpace <|-- Bathroom
IfcSpace <|-- RestRoom
IfcSpace <|-- Canteen
IfcSpace <|-- Cafeteria
IfcSpace <|-- Room
IfcSpace <|-- Desk
IfcSpace <|-- OpenSpace

IfcBuildingStorey <|-- Floor
Floor <|-- Subterranean
Floor <|-- Ground

IfcDistributionElement <|-- IfcDistributionControlElement
IfcDistributionControlElement <|-- IfcActuator
IfcDistributionControlElement <|-- IfcAlarm
IfcDistributionControlElement <|-- IfcController
IfcDistributionControlElement <|-- IfcFlowInstrument
IfcDistributionControlElement <|-- IfcProtectiveDeviceTrippingUnit
IfcDistributionControlElement <|-- IfcSensor
IfcDistributionControlElement <|-- IfcUnitaryControlElement

PhysicalMedium <|-- Oil
PhysicalMedium <|-- Gas
PhysicalMedium <|-- Water
PhysicalMedium <|-- Air
PhysicalMedium <|-- Steam
PhysicalMedium <|-- Radiation

IfcFlowMovingDevice --> PhysicalMedium: hit2gap:transports
IfcEnergyConversionDevice --> PhysicalMedium: hit2gap:consumes
IfcEnergyConversionDevice --> PhysicalMedium: hit2gap:produces
IfcFlowStorageDevice --> PhysicalMedium: hit2gap:stores
IfcFlowController --> PhysicalMedium: hit2gap:controls
IfcFlowTerminal --> PhysicalMedium: hit2gap:consumes

IfcFlowInstrument --> IfcFlowInstrumentType: owl:equivalentClass
IfcSensor --> IfcSensorType: owl:equivalentClass
IfcFlowStorageDevice --> IfcFlowStorageDeviceType: owl:equivalentClass
IfcActuator --> IfcActuatorType: owl:equivalentClass
IfcAlarm --> IfcAlarmType: owl:equivalentClass
IfcController --> IfcControllerType: owl:equivalentClass
@enduml
