@startuml
skinparam dpi 600

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

class IfcActor <<IFC>> {
  id xsd:string
  name xsd:string
}

class IfcOccupant <<IFC>>{
  age xsd:double
  gender xsd:string
  lifestyle xsd:string
  jobType xsd:string
}

class User <<HIT2GAP>>{

}

class Notification <<HIT2GAP>>{

}

class Report <<HIT2GAP>>{

}

class Recommendation <<HIT2GAP>>{

}

class Feedback <<HIT2GAP>>{

}

class Alert <<HIT2GAP>>{

}


class IfcSpatialStructureElement <<IFC>>{

}

class IfcSensor <<ifc4>>
class IfcSensorType <<ifc>>

class FeatureOfInterest <<SSN>>{

}

class Observation <<SSN>> {
  externalStorageID xsd:string
}

class MobileBuildingApplianceLocationObservation <<bem>>
class MobileBuildingAppliance <<bem>>

class Property <<SSN>> {

}

class EconomicProperties <<bem>>
class PhysicProperties <<bem>>
class OccupantStateProperties <<bem>>

class SensorOutput <<SSN>>{

}

class ObservationValue <<SSN>>{

}


class Instant <<Time>>{

}

class DateTimeInterval <<Time>>{

}

class IfcBuilding <<IFC>>{

}

class SampledFeatures <<OGC>>{

}

class SamplingFeatures <<OGC>>{

}

class IfcSpatialZone <<ifc4>>{

}


class ZoneElement <<HIT2GAP>>{

}

class Driver <<HIT2GAP>>{

}


class OccupantBehaviour<<HIT2GAP>>{

}

class OccupantCharacteristics <<HIT2GAP>>{
  startWorkTime xsd:DateTime
  endWorkTime xsd:DateTime
}

class EnergyFrugal <<HIT2GAP>>{

}

class EnergyProfligate <<HIT2GAP>>{

}

class EnergyIndiferent <<HIT2GAP>>{

}

class EnvironmentalBuildingFactors <<HIT2GAP>>{

}

class System <<SSN>>{

}

class BuildingState <<HIT2GAP>>{

}

class BuildingSimpleState <<HIT2GAP>>{

}

class BuildingComplexState <<HIT2GAP>>{

}

class EnergyState <<HIT2GAP>>{

}

class Sensor <<SSN>>{

}

class TimeBehaviour <<HIT2GAP>>{

}

class Season <<HIT2GAP>>{

}

class Winter <<(I,orchid) HIT2GAP>>{

}
class Spring <<(I,orchid) HIT2GAP>>{

}
class Summer <<(I,orchid) HIT2GAP>>{

}
class Autumn <<(I,orchid) HIT2GAP>>{

}

class DayOfWeek <<Time>>{

}

class Needs <<HIT2GAP>>{

}

class EnergyEfficiencyState <<HIT2GAP>>{

}

class ComfortState <<HIT2GAP>>{

}

class OccupantComfort <<HIT2GAP>>{

}

class OccupantDiscomfort <<HIT2GAP>>{

}


class ThermalComfort <<HIT2GAP>>{

}


class ISOAdaptiveComfort <<HIT2GAP>>{

}

class ASHRAEAdaptiveComfort <<HIT2GAP>>{

}

class ASHRAEAdaptiveEnvelope <<HIT2GAP>>{

}

class OtherComfortEnvelope <<HIT2GAP>>{

}


class VisualComfort <<HIT2GAP>>{

}

class AcousticComfort <<HIT2GAP>>{

}

class IAQ <<HIT2GAP>>{

}

class OccupantPreference <<HIT2GAP>>{
  id xsd:string
  minValue xsd:double
  maxValue xsd:double
}

class Luminosity <<I,orchid) HIT2GAP>>{

}

class Noise <<I,orchid) HIT2GAP>>{

}

class Temperature <<I,orchid) HIT2GAP>>{

}

class Actions <<HIT2GAP>>{

}

class SystemActions<<HIT2GAP>>{

}

class Inaction <<HIT2GAP>>{

}

class Modality <<HIT2GAP>>{

}

class SMS <<(I,orchid) HIT2GAP>>{

}
class Email <<(I,orchid) HIT2GAP>>{

}
class Phone <<(I,orchid) HIT2GAP>>{

}

class Role <<HIT2GAP>>{

}
class Manager <<(I,orchid) HIT2GAP>>{

}
class Owner <<(I,orchid) HIT2GAP>>{

}
class Technician <<(I,orchid) HIT2GAP>>{

}

class Privacy <<HIT2GAP>>{

}

class OccupantAttitude <<HIT2GAP>>{
}

class BehaviourModel <<HIT2GAP>>{
}

class ActivityModel <<HIT2GAP>>{
}

class EventModel <<HIT2GAP>>{
}

class EquipmentModel <<HIT2GAP>>{
}

class Unit <<QUDT>>{
}

class Event <<HIT2GAP>>
class ModelResult <<HIT2GAP>>
class Indicator <<HIT2GAP>>
class Status <<HIT2GAP>>
class Function <<HIT2GAP>>
class Constraints <<HIT2GAP>>
class Probability <<HIT2GAP>>
class Context <<HIT2GAP>>

class IfcActuator <<ifc4>>
class IfcActuatorType <<ifc>>

Context --> Indoor: hit2gap:isAssignedTo
Context --> Outdoor: hit2gap:isAssignedTo

note top of Driver
stimulating factors that provoke energyrelated
occupant behavior.
end note

note bottom of EnvironmentalBuildingFactors
We have to restrict the observation values to those systems
values (temperature, humidity, etc)
end note

note top of Needs
there are certain physical needs that people must meet in order to survive. There are
others that make people more comfortable. In the specific ways they
strive to meet these needs, people are different
end note

note top of ThermalComfort
combination of indoor air temperature and humidity, surrounding surface temperatures, indoor
air velocity, activity level, incident radiation and clothing level of the occupant
end note

note top of VisualComfort
comfort such as not being subjected to glare, excessive contrast or unacceptable levels of brightness
end note

note bottom of AcousticComfort
With the level of background noise within an acceptable range
end note

note bottom of IAQ
Indoor environmental health, meaning good IAQ or humidity
end note

note top of ComfortState
Comfort state is the result from the violation of user needs measured through the
drivers.
end note

/'
Description of the Ifc Actor relations
'/

IfcActor <|-- User
IfcActor--> Role: hit2gap:hasRole
IfcActor --> Sensor:hit2gap:acts
IfcActor --> IfcActuator:hit2gap:acts

Role ..[#orchid] Manager
Role ..[#orchid] Owner
Role ..[#orchid] Technician
User <|-- IfcOccupant

/'
Description of Feedback and Reporting
'/

Feedback <|-- Report
Notification <|-- Alert
Notification <|-- Recommendation
User --> Modality: hit2gap:prefers
Modality ..[#orchid] SMS
Modality ..[#orchid] Email
Modality ..[#orchid] Phone

User --> Notification:hit2gap:receives
User --> Feedback:hit2gap:concerns


/'
Description of the SSN model adapted to buildign observation
'/

FeatureOfInterest <|-- SampledFeatures
FeatureOfInterest <|-- SamplingFeatures
Observation --> FeatureOfInterest: ssn:featureOfInterest
Observation--> SensorOutput: ssn:observationResult
SensorOutput --> ObservationValue: ssn_hasValue
ObservationValue --> Unit:qudt:unit
Observation --> Instant: ssn:observationResultTime
Observation --> DateTimeInterval: ssn:observationResultTime
FeatureOfInterest --> Property: ssn:hasProperty

Observation <|-- MobileBuildingApplianceLocationObservation
MobileBuildingAppliance --> MobileBuildingApplianceLocationObservation: hit2gap:wasLocated

SampledFeatures <|-- IfcBuilding
IfcSpatialElement <|-- IfcSpatialZone
IfcSpatialElement<|-- ZoneElement

/'
Definition of the Property subclasses
'/

Property <|-- OccupantStateProperties
Property <|-- EconomicProperties
Property <|-- PhysicProperties

/'
Description of building states
'/
IfcBuilding --> BuildingState:hasState
System --> BuildingState: hit2gap:hasState
BuildingState <|-- BuildingSimpleState
BuildingState <|-- BuildingComplexState
BuildingComplexState <|-- EnergyState
BuildingComplexState <|-- ComfortState
ComfortState <|-- OccupantComfort
ComfortState <|-- OccupantDiscomfort
System --> System:ssn:hasSubsystem
System <|-- Sensor
Sensor --> Observation:ssn:observedBy
Sensor --> Property:ssn:observes
IfcSensor --> Sensor: owl:equivalentClass

Observation <|-- Driver

/'
Description of driver (old SIM_MOD)
'/

Driver <|-- BehaviourModel
Driver <|-- ActivityModel
Driver <|-- EventModel
Driver <|-- EquipmentModel

EventModel --> Event: hit2gap:isBasedOn
EquipmentModel --> EnvironmentalBuildingFactors: hit2gap:isBasedOn
BehaviourModel --> TimeBehaviour: hit2gap:isBasedOn
BehaviourModel --> OccupantBehaviour: hit2gap:isBasedOn

TimeBehaviour <|-- Season
TimeBehaviour <|-- Instant
TimeBehaviour <|-- DayOfWeek
TimeBehaviour <|-- DateTimeInterval
Season ..[#orchid] Winter
Season..[#orchid] Summer
Season..[#orchid] Spring
Season..[#orchid] Autumn

Event --> SensorOutput: hit2gap:associatedTo
Driver --> ModelResult: hit2gap:ModelResult
Driver --> Indicator: hit2gap:hasIndicator
Driver --> Status: hit2gap:hasStatus
Driver --> Function: hit2gap:hasFunction

Event --> Constraints: hit2gap:hasContraints
Event --> Probability: hit2gap:hasProbability
Event --> Context: hit2gap:hasContext

Context --> Indoor: hit2gap:isAssignedTo
Context --> Outdoor: hit2gap:isAssignedTo

/'
Definition of occupant attitude and IfcOccupants and their
corresponding roles.
'/

OccupantAttitude <|-- EnergyFrugal
OccupantAttitude <|-- EnergyProfligate
OccupantAttitude <|-- EnergyIndiferent


IfcOccupant --> OccupantCharacteristics: hit2gap:hasOccupantCharacteristics
IfcOccupant --> Needs: hit2gap:hasComfortRequirements
IfcOccupant --> OccupantAttitude:hit2gap:hasOccupantAttitude
IfcOccupant --> Actions: hit2gap:performsAction
IfcOccupant --> OccupantBehaviour: hit2gap:hasBehaviour

/'
 Definition of the occupant needs and comfort
'/
Needs <|-- Privacy
Needs <|-- OccupantPreference
OccupantPreference ..[#orchid] Luminosity
OccupantPreference ..[#orchid] Noise
OccupantPreference ..[#orchid] Temperature

Needs <|-- ThermalComfort
Needs<|-- VisualComfort
Needs <|-- AcousticComfort
Needs <|-- IAQ

ThermalComfort<|-- ISOAdaptiveComfort
ThermalComfort<|-- ASHRAEAdaptiveComfort
ThermalComfort<|-- ASHRAEAdaptiveEnvelope
ThermalComfort<|-- OtherComfortEnvelope

/'
 Definition of the actions
'/

Actions <|-- SystemActions
Actions <|-- Inaction
Actions <|-- Feedback
Actions <|-- OccupantBeaviour

Actions --> OccupantDiscomfort:hit2gap:provoke
SystemActions --> IfcDistributionControlElement:hit2gap:changes
IfcDistributionControlElement --> Alert: hit2gap:receivesAlert
SystemActions --> Sensor: hit2gap:actuateOver
Actions --> IfcSpatialStructureElement: hit2gap:change

IfcSensor --> IfcSensorType: owl:equivalentClass
IfcActuator --> IfcActuatorType: owl:equivalentClass

@enduml
