@startuml

scale 0.35

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}

skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green


class Property <<ssn>>

class OccupantProperties <<hit2gap>>

class Stress <<hit2gap>>
class Pulse <<hit2gap>>

Property <|-- OccupantProperties


OccupantProperties <|-- Stress 
OccupantProperties <|-- Pulse


@enduml
