@startuml

scale 0.35

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

/'
  Definition of the Properties Medium
'/

class Property <<ssn>>
class EconomicProperties <<hit2gap>>
class PhysicProperties <<hit2gap>>

class Cost <<hit2gap>>
class Investment <<hit2gap>>

class Climate <<hit2gap>>
class Tropical <<(I,orchid),hit2gap>>
class TropicalRainforest <<(I,orchid),hit2gap>>
class TropicalMonsoon <<(I,orchid),hit2gap>>
class TropicalSavanna <<(I,orchid),hit2gap>>

class Arid <<(I,orchid),hit2gap>>
class HotDesert <<(I,orchid),hit2gap>>
class ColdDesert <<(I,orchid),hit2gap>>
class MildDesert <<(I,orchid),hit2gap>>
class HotSemiArid <<(I,orchid),hit2gap>>
class ColdSemiArid <<(I,orchid),hit2gap>>
class MildSemiArid <<(I,orchid),hit2gap>>

class Temperate <<(I,orchid),hit2gap>>
class HumidSubtropical <<(I,orchid),hit2gap>>
class TemperateOceanic <<(I,orchid),hit2gap>>
class SubpolarOceanic <<(I,orchid),hit2gap>>
class MonsoonInfluencedHumidSubtropical <<(I,orchid),hit2gap>>
class TemperateOceanicWithDryWinters <<(I,orchid),hit2gap>>
class SubPolarOceanicWithDryWinters <<(I,orchid),hit2gap>>
class HotSummerMediterranean <<(I,orchid),hit2gap>>
class WarnSummerMediterranean <<(I,orchid),hit2gap>>
class CoolSummerMediterranean <<(I,orchid),hit2gap>>


class Continental <<(I,orchid),hit2gap>>
class HotSummerHumidContinental <<(I,orchid),hit2gap>>
class WarmSummerHumidContinental <<(I,orchid),hit2gap>>
class Subartic <<(I,orchid),hit2gap>>
class ExtremelyColdSubartic <<(I,orchid),hit2gap>>
class MonsoonInfluencedHotSummerHumidContinental <<(I,orchid),hit2gap>>
class MonsoonInfluencedWarmSummerHumidContinental <<(I,orchid),hit2gap>>
class MonsoonInfluencedSubartic <<(I,orchid),hit2gap>>
class MonsoonInfluencedExtremelyColdSubarctic <<(I,orchid),hit2gap>>
class HotDrySummerContinental <<(I,orchid),hit2gap>>  
class WarmDrySummerContinental <<(I,orchid),hit2gap>>  
class DrySummerSubarctic <<(I,orchid),hit2gap>>  
class ExtremelyColdDrySummerSubarctic <<(I,orchid),hit2gap>>  

class Polar <<(I,orchid),hit2gap>>
class MildTundra <<(I,orchid),hit2gap>>
class FrostColdTundra <<(I,orchid),hit2gap>>
class IceCap <<(I,orchid),hit2gap>>
class Air <<hit2gap>>
class Water <<hit2gap>>
class Wind <<hit2gap>>
class WindOrientation <<hit2gap>>
class WindSpeed <<hit2gap>>
class Steam <<hit2gap>>
class State <<hit2gap>>
class Area <<hit2gap>>
class Capacity <<hit2gap>>
class ProductionCapacity <<hit2gap>>
class Color <<hit2gap>>
class Conductivity <<hit2gap>>
class Co2Rate <<hit2gap>>
class Density <<hit2gap>>
class Humidity <<hit2gap>>
class Depth <<hit2gap>>
class EquivalentDepth <<hit2gap>>
class Energy <<hit2gap>>
class ElectricEnergy <<hit2gap>>
class HeatFluxEnergy <<hit2gap>>
class Evaporation <<hit2gap>>
class Condensation <<hit2gap>>
class Medium <<hit2gap>>
class Precipitation <<hit2gap>>
class Pressure <<hit2gap>>
class Position <<hit2gap>>
class Longitude <<hit2gap>>
class Latitude <<hit2gap>>
class Altitude <<hit2gap>>
class Radiation <<hit2gap>>
class LightRadiation <<hit2gap>>
class IncidentRadiation <<hit2gap>>
class AbsorbedIncidentRadiation <<hit2gap>>
class ReflectedIncidentradiation <<hit2gap>>
class AbsorbedScatteredIncidentRadiation <<hit2gap>>
class TransmittedIncidentRadiation <<hit2gap>>
class Tension <<hit2gap>>
class Rainfall <<hit2gap>>
class Reflectivity <<hit2gap>>
class Shape <<hit2gap>>
class CrossSection <<hit2gap>>
class Height <<hit2gap>>
class Length <<hit2gap>>
class Slope <<hit2gap>>
class Weight <<hit2gap>>
class Width <<hit2gap>>
class Intensity <<hit2gap>>
class Speed <<hit2gap>>
class Temperature  <<hit2gap>>
class Time <<hit2gap>>
class Transparency <<hit2gap>>
class Velocity <<hit2gap>>
class Visibility <<hit2gap>>
class Volume <<hit2gap>>
class Discharge <<hit2gap>>
class Flow <<hit2gap>>
class Inflow <<hit2gap>>
class Outflow <<hit2gap>>
class AirMedium <<hit2gap>>
class AirQuality <<hit2gap>>
/'
  Definition of the properties hierarchy
'/

Property <|-- EconomicProperties
Property <|-- PhysicProperties

EconomicProperties <|-- Cost
EconomicProperties <|-- Investment

PhysicProperties <|-- Air
PhysicProperties <|-- Water
PhysicProperties <|-- Steam
PhysicProperties <|-- State
PhysicProperties <|-- Area
PhysicProperties <|-- Capacity
Capacity<|-- ProductionCapacity
PhysicProperties <|-- Color
PhysicProperties <|-- Conductivity
PhysicProperties <|-- Density
PhysicProperties <|-- Depth
PhysicProperties <|-- Position
Position <|-- Longitude
Position <|-- Latitude
Position <|-- Altitude
PhysicProperties <|--EquivalentDepth
PhysicProperties <|-- Energy
Energy<|-- ElectricEnergy
Energy<|-- HeatFluxEnergy
PhysicProperties <|-- Wind
Wind <|-- WindOrientation
Wind <|-- WindSpeed 
PhysicProperties <|-- Evaporation
PhysicProperties <|-- Condensation
PhysicProperties <|-- Co2Rate
PhysicProperties <|-- Humidity
PhysicProperties <|-- Medium
PhysicProperties <|-- Precipitation
PhysicProperties <|-- Pressure
PhysicProperties <|-- Radiation
PhysicProperties <|-- Tension
Radiation<|-- IncidentRadiation
Radiation<|-- LightRadiation
IncidentRadiation<|-- AbsorbedIncidentRadiation
IncidentRadiation<|-- ReflectedIncidentradiation
IncidentRadiation<|-- AbsorbedScatteredIncidentRadiation
IncidentRadiation<|-- TransmittedIncidentRadiation
PhysicProperties <|-- Rainfall
PhysicProperties <|-- Reflectivity
PhysicProperties <|-- Intensity
PhysicProperties <|-- Shape
Shape<|-- CrossSection
Shape<|-- Height
Shape<|-- Length
Shape<|-- Slope
Shape<|-- Weight
Shape<|-- Width
PhysicProperties <|-- Speed
PhysicProperties <|-- Temperature
PhysicProperties <|-- Time
PhysicProperties <|-- Transparency
PhysicProperties <|-- Velocity
PhysicProperties <|-- Visibility
PhysicProperties <|-- Volume
Volume<|-- Discharge
Volume<|-- Flow
Flow<|-- Inflow
Flow<|-- Outflow
Medium<|-- AirMedium
Air<|-- AirQuality
PhysicProperties <|-- Climate

Climate ..[#orchid] Tropical
Climate ..[#orchid] Arid
Climate ..[#orchid] Temperate
Climate ..[#orchid] Continental
Climate ..[#orchid] Polar

Tropical ..[#orchid] TropicalRainforest 
Tropical ..[#orchid] TropicalMonsoon 
Tropical ..[#orchid] TropicalSavanna 

Arid ..[#orchid] HotDesert 
Arid ..[#orchid] ColdDesert 
Arid ..[#orchid] MildDesert 
Arid ..[#orchid] HotSemiArid 
Arid ..[#orchid] ColdSemiArid 
Arid ..[#orchid] MildSemiArid 

Temperate ..[#orchid] HumidSubtropical
Temperate ..[#orchid] TemperateOceanic 
Temperate ..[#orchid] SubpolarOceanic 
Temperate ..[#orchid] MonsoonInfluencedHumidSubtropical
Temperate ..[#orchid] TemperateOceanicWithDryWinters 
Temperate ..[#orchid] SubPolarOceanicWithDryWinters 
Temperate ..[#orchid] HotSummerMediterranean 
Temperate ..[#orchid] WarnSummerMediterranean
Temperate ..[#orchid] CoolSummerMediterranean

Continental ..[#orchid] HotSummerHumidContinental 
Continental ..[#orchid] WarmSummerHumidContinental 
Continental ..[#orchid] Subartic 
Continental ..[#orchid] ExtremelyColdSubartic 
Continental ..[#orchid] MonsoonInfluencedHotSummerHumidContinental 
Continental ..[#orchid] MonsoonInfluencedWarmSummerHumidContinental 
Continental ..[#orchid] MonsoonInfluencedSubartic
Continental ..[#orchid] MonsoonInfluencedExtremelyColdSubarctic 
Continental ..[#orchid] HotDrySummerContinental 
Continental ..[#orchid] WarmDrySummerContinental 
Continental ..[#orchid] DrySummerSubarctic 
Continental ..[#orchid] ExtremelyColdDrySummerSubarctic  

Polar ..[#orchid] MildTundra 
Polar ..[#orchid] FrostColdTundra 
Polar ..[#orchid] IceCap

@enduml
