@startuml

scale 0.6

skinparam class {
  ArrowColor DarkBlue
  ArrowFontColor DarkBlue
  BackgroundColor LightBlue
  BorderColor DarkGrey
}
skinparam dpi 300
skinparam stereotypeCBackgroundColor Wheat
skinparam classAttributeFontColor  Green

class IfcOccupant <<IFC>>{
  age xsd:double
  gender xsd:string
  lifestyle xsd:string
  jobType xsd:string
}

class OccupantAttitude <<HIT2GAP>>{
}


class OccupantCharacteristics <<HIT2GAP>>{
  startWorkTime xsd:DateTime
  endWorkTime xsd:DateTime
}


class OccupantBehaviour <<HIT2GAP>>{

}


class Needs <<HIT2GAP>>{

}

class EnergyFrugal <<HIT2GAP>>{

}

class EnergyProfligate <<HIT2GAP>>{

}

class EnergyIndiferent <<HIT2GAP>>{

}

OccupantAttitude <|-- EnergyFrugal
OccupantAttitude <|-- EnergyProfligate
OccupantAttitude <|-- EnergyIndiferent


IfcOccupant --> OccupantCharacteristics: hit2gap:hasOccupantCharacteristics
IfcOccupant --> Needs: hit2gap:hasComfortRequirements
IfcOccupant --> OccupantAttitude:hit2gap:hasOccupantAttitude
IfcOccupant --> Actions: hit2gap:performsAction
IfcOccupant --> OccupantBehaviour: hit2gap:hasBehaviour



@enduml
